import React from 'react'
import Layout from '@/components/Layout'
import { Box, Typography } from '@mui/material'

const Contact = () => {
  return (
    <Layout title='Contact'>
      <Box>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>{' '}
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
        <Typography variant='body1'>In this project I refactored code that was previously given raw without styles applied. After coding the design per a given design format, first using block / inline-block I refactored to display flex. Being able to be versitile in current designing methods and legacy design methods demonstrates true understaning of CSS implementation.</Typography>
      </Box>
    </Layout>
  )
}

export default Contact
